export const dashboardMsgProfiles = [
  {
    profile: "/assets/dummyImages/profilePic.png",
    firstName: "Ignatio ",
    lastName: "Adamson",
  },
  {
    profile: "",
    firstName: "Imokedu",
    lastName: "Christine",
  },
  {
    profile: "/assets/dummyImages/profilePic.png",
    firstName: "Harry ",
    lastName: "Kanen",
  },
];

export const expertise = [
  "Web-view app/apps that need backends",
  "Picture gallery app, Social Media app",
  "Payment integration",
  "Map based tracking, GPS, Core data",
  "Calendar based app",
];

export const certificatesDetails = [
  {
    certificateURL: "/assets/images/privateExpertImg1.png",
    issuingOrg: "Painters Association of Nigeria",
    verificationNumber: "1234567890",
    issuingDate: "12/01/2009",
    expiringDate: "none",
  },
  {
    certificateURL: "/assets/images/privateExpertImg.png",
    issuingOrg: "Painters Leaders of Nigeria",
    verificationNumber: "1234567890",
    issuingDate: "12/01/2009",
    expiringDate: "none",
  },
];

export const messages = [
  {
    day: "Monday",
    msg: [
      {
        who: "sender",
        content: [
          "Hi! My name is Simsisola Adeking. I’m new on this app and you have been assigned as my success coach. I’m looking forward to working with you. Nice to meet you.",
        ],
        time: "12:00am",
        seen: "Sent at",
      },
      {
        who: "reciever",
        content: [
          "Don’t you love the Tech1m web app. King Ayo 👑 and friends designed it ☺️",
        ],
        time: "12:00am",
        seen: "Read at",
      },
      {
        who: "sender",
        content: [
          "Thanks for agreeing to take this project with me i really appreciate it.",
        ],
        time: "12:00am",
        seen: "Sent at",
      },
    ],
  },
  {
    day: "Tuesday",
    msg: [
      {
        who: "sender",
        content: [
          " as my success coach. I’m looking forward to working with you. Nice to meet you.",
        ],
        time: "12:00am",
        seen: "Sent at",
      },
      {
        who: "reciever",
        content: [
          "Lol, Its a nigerian name 💪🏼💪🏼",
          "success coach. I’m looking forward to working with you. Nice to meet you.",
        ],
        time: "12:00am",
        seen: "Read at",
      },
      {
        who: "sender",
        content: ["Oh wow! , Thats a funny name for a dog. Don’t you think."],
        time: "12:00am",
        seen: "Sent at",
      },
    ],
  },
];

export const allData = [
  {
    id: "728ed52f",
    amount: 10000,
    user: "Wills Chisom",
    status: "completed",
    email: "m@example.com",
    type: "local bank",
    network: "MTN",
    number: "08034568695",
    cable: "Credit",
    betShop: "Sportybet",
    electricity: "Eko prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "489e1d442",
    amount: 125,
    user: "Ola Wale",
    status: "completed",
    email: "lyth@gmail.com",
    type: "walletwise",
    network: "GLO",
    number: "08034568695",
    cable: "Credit",
    betShop: "Sportybet",
    electricity: "Eko prepaid",
    airline: "Arik Air Book",
    giftCard: "Amazon",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "4839e1d42",
    amount: 12005,
    user: "John Chisom",
    status: "cancelled",
    email: "example@gmail.com",
    type: "local bank",
    network: "MTN",
    number: "08034568695",
    cable: "Credit",
    betShop: "Sportybet",
    electricity: "Eko prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "489e1d422",
    amount: 2005,
    user: "Nedz Chinedu",
    status: "completed",
    email: "exam@gmail.com",
    type: "local bank",
    network: "MTN",
    number: "08034568695",
    cable: "Credit",
    betShop: "Sportybet",
    electricity: "Eko prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "48922d42",
    amount: 2225,
    user: "Tega Chisom",
    status: "completed",
    email: "fly@gmail.com",
    type: "local bank",
    network: "Airtel",
    number: "08034568695",
    cable: "Debit",
    betShop: "bet9ja",
    electricity: "PHCN prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "48931d4234",
    amount: 12005,
    user: "Miracle Kelechi",
    status: "cancelled",
    email: "victor@gmail.com",
    type: "local bank",
    network: "MTN",
    number: "08034568695",
    cable: "Credit",
    betShop: "Sportybet",
    electricity: "Eko prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "489e1d4244",
    amount: 125,
    user: "Michael Chisom",
    status: "cancelled",
    email: "zagadate@gmail.com",
    type: "walletwise",
    network: "MTN",
    number: "08034568695",
    cable: "Credit",
    betShop: "Sportybet",
    electricity: "Eko prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "489e1d4774",
    amount: 125,
    user: "Wills Victor",
    status: "completed",
    email: "thole@gmail.com",
    type: "walletwise",
    network: "Airtel",
    number: "08034568695",
    cable: "Debit",
    betShop: "bet9ja",
    electricity: "PHCN prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "489e64244",
    amount: 125,
    user: "Uju Ojinnaka",
    status: "cancelled",
    email: "gol@gmail.com",
    type: "walletwise",
    network: "Airtel",
    number: "08034568695",
    cable: "Debit",
    betShop: "bet9ja",
    electricity: "PHCN prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "48944d4244",
    amount: 125,
    status: "completed",
    user: "Jaja Mildred",
    email: "sluu@gmail.com",
    type: "walletwise",
    network: "Airtel",
    number: "08034568695",
    cable: "Debit",
    betShop: "bet9ja",
    electricity: "PHCN prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "489443244",
    amount: 125,
    user: "Blessing  Igri",
    status: "cancelled",
    email: "judah@gmail.com",
    type: "walletwise",
    network: "Airtel",
    number: "08034568695",
    cable: "Debit",
    betShop: "bet9ja",
    electricity: "PHCN prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
  {
    id: "48244",
    amount: 125,
    user: "Favour Chudy",
    status: "cancelled",
    email: "kelechi@gmail.com",
    type: "walletwise",
    network: "Airtel",
    number: "08034568695",
    cable: "Debit",
    betShop: "bet9ja",
    electricity: "PHCN prepaid",
    airline: "Dana Air Book",
    giftCard: "Apple",
    date: "2nd Aug, 2024",
    virtualCard: "Cash token",
    hotel: "Pinewood",
  },
];
