export const category = [
  "Agriculture",
  "Artisan",
  "Construction",
  "Education",
  "Entertainment",
  "Event Management",
  "Food/restaurant",
  "Information Management",
  "medical",
  "Manufacturing",
  "minning",
  "professional service",
  "real estate",
  "utility",
  "Waste Management",
];

export const serviceList = [
  "Project Manager",
  "Site Supervisor",
  "Architect",
  "Civil Engineer",
  "Structural Engineer",
  "Electrician",
  "Bricklayer",
  "Plumber",
  "Carpenter",
  "Mason",
  "Painter",
  "Welder",
  "Steel Fixer",
  "Crane Operator",
  "Laborer",
  "Surveyor",
  "Safety Officer",
  "Others",
];

export const insuranceOptions = [
  "General Liability Insurance",
  "Professional Liability Insurance",
  "Contractor’s All Risk Insurance",
  "Performance Bond",
  "Delay in Start-Up Insurance",
  "Health Insurance",
  "Tools and Equipment Insurance",
  "Commercial Auto Insurance",
];

export const privateExpert = [
  { title: "Investigator", url: "/" },
  { title: "Supervisor", url: "/" },
  { title: "Project manager", url: "/" },
  { title: "Private expert", url: "/become-expert" },
];

export const footerLinks = [
  {
    title: "Company",
    links: [
      { name: "About Us", link: "/about-us" },
      { name: "Privacy Policy", link: "/privacy-policy" },
      { name: "Terms of Use", link: "/terms" },
      { name: "Cookie Policy", link: "/cookie-policy" },
    ],
  },
  {
    title: "Support",
    links: [
      { name: "How it works", link: "/how" },
      { name: "FAQ", link: "/faq" },
      { name: "Guides", link: "/guides" },
      { name: "Help Center", link: "/help-center" },
    ],
  },
  {
    title: "Community",
    links: [
      { name: "Blogs", link: "/blogs" },
      { name: "Press & News", link: "/news" },
      { name: "Helpful Tips", link: "/tips" },
      { name: "Customer Testimonial", link: "/testimonial" },
    ],
  },
];

export const landingPageLinks = [
  {
    id: 1,
    name: "Hire Workers",
    link: "/hire-experts",
  },
  {
    id: 2,
    name: "Find Jobs",
    link: "/find-job",
  },
  {
    id: 3,
    name: "Buy Materials",
    link: "/buy-materials",
  },
];

export const jobOptions = [
  { id: 1, label: "Bricklayer" },
  { id: 2, label: "Plumber" },
  { id: 3, label: "Painter" },
  { id: 4, label: "Others" },
];

export const languages = [
  { value: "english", label: "English" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "chinese", label: "Chinese" },
  { value: "arabic", label: "Arabic" },
  { value: "russian", label: "Russian" },
  { value: "portuguese", label: "Portuguese" },
  { value: "japanese", label: "Japanese" },
  { value: "korean", label: "Korean" },
  { value: "italian", label: "Italian" },
  { value: "dutch", label: "Dutch" },
  { value: "swedish", label: "Swedish" },
  { value: "afrikaans", label: "Afrikaans" },
  { value: "albanian", label: "Albanian" },
  { value: "amharic", label: "Amharic" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "bengali", label: "Bengali" },
  { value: "burmese", label: "Burmese" },
  { value: "catalan", label: "Catalan" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "estonian", label: "Estonian" },
  { value: "igbo", label: "Igbo" },
  { value: "Hausa", label: "Hausa" },
  { value: "Yoruba", label: "Yoruba" },
];

export const countries = [
  { label: "Afghanistan", value: "Afghanistan" },
  { label: "Albania", value: "Albania" },
  { label: "Algeria", value: "Algeria" },
  { label: "Andorra", value: "Andorra" },
  { label: "Angola", value: "Angola" },
  { label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { label: "Argentina", value: "Argentina" },
  { label: "Armenia", value: "Armenia" },
  { label: "Australia", value: "Australia" },
  { label: "Austria", value: "Austria" },
  { label: "Azerbaijan", value: "Azerbaijan" },
  { label: "Bahamas", value: "Bahamas" },
  { label: "Bahrain", value: "Bahrain" },
  { label: "Bangladesh", value: "Bangladesh" },
  { label: "Barbados", value: "Barbados" },
  { label: "Belarus", value: "Belarus" },
  { label: "Belgium", value: "Belgium" },
  { label: "Belize", value: "Belize" },
  { label: "Benin", value: "Benin" },
  { label: "Bhutan", value: "Bhutan" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { label: "Botswana", value: "Botswana" },
  { label: "Brazil", value: "Brazil" },
  { label: "Brunei", value: "Brunei" },
  { label: "Bulgaria", value: "Bulgaria" },
  { label: "Burkina Faso", value: "Burkina Faso" },
  { label: "Burundi", value: "Burundi" },
  { label: "Cabo Verde", value: "Cabo Verde" },
  { label: "Cambodia", value: "Cambodia" },
  { label: "Cameroon", value: "Cameroon" },
  { label: "Canada", value: "Canada" },
  { label: "Central African Republic", value: "Central African Republic" },
  { label: "Chad", value: "Chad" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Colombia", value: "Colombia" },
  { label: "Comoros", value: "Comoros" },
  { label: "Congo", value: "Congo" },
  { label: "Costa Rica", value: "Costa Rica" },
  { label: "Croatia", value: "Croatia" },
  { label: "Cuba", value: "Cuba" },
  { label: "Cyprus", value: "Cyprus" },
  { label: "Czech Republic", value: "Czech Republic" },
  {
    label: "Democratic Republic of the Congo",
    value: "Democratic Republic of the Congo",
  },
  { label: "Denmark", value: "Denmark" },
  { label: "Djibouti", value: "Djibouti" },
  { label: "Dominica", value: "Dominica" },
  { label: "Dominican Republic", value: "Dominican Republic" },
  { label: "East Timor", value: "East Timor" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "Egypt", value: "Egypt" },
  { label: "El Salvador", value: "El Salvador" },
  { label: "Equatorial Guinea", value: "Equatorial Guinea" },
  { label: "Eritrea", value: "Eritrea" },
  { label: "Estonia", value: "Estonia" },
  { label: "Eswatini", value: "Eswatini" },
  { label: "Ethiopia", value: "Ethiopia" },
  { label: "Fiji", value: "Fiji" },
  { label: "Finland", value: "Finland" },
  { label: "France", value: "France" },
  { label: "Gabon", value: "Gabon" },
  { label: "Gambia", value: "Gambia" },
  { label: "Georgia", value: "Georgia" },
  { label: "Germany", value: "Germany" },
  { label: "Ghana", value: "Ghana" },
  { label: "Greece", value: "Greece" },
  { label: "Grenada", value: "Grenada" },
  { label: "Guatemala", value: "Guatemala" },
  { label: "Guinea", value: "Guinea" },
  { label: "Guinea-Bissau", value: "Guinea-Bissau" },
  { label: "Guyana", value: "Guyana" },
  { label: "Haiti", value: "Haiti" },
  { label: "Honduras", value: "Honduras" },
  { label: "Hungary", value: "Hungary" },
  { label: "Iceland", value: "Iceland" },
  { label: "India", value: "India" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Iran", value: "Iran" },
  { label: "Iraq", value: "Iraq" },
  { label: "Ireland", value: "Ireland" },
  { label: "Israel", value: "Israel" },
  { label: "Italy", value: "Italy" },
  { label: "Ivory Coast", value: "Ivory Coast" },
  { label: "Jamaica", value: "Jamaica" },
  { label: "Japan", value: "Japan" },
  { label: "Jordan", value: "Jordan" },
  { label: "Kazakhstan", value: "Kazakhstan" },
  { label: "Kenya", value: "Kenya" },
  { label: "Kiribati", value: "Kiribati" },
  { label: "Kosovo", value: "Kosovo" },
  { label: "Kuwait", value: "Kuwait" },
  { label: "Kyrgyzstan", value: "Kyrgyzstan" },
  { label: "Laos", value: "Laos" },
  { label: "Latvia", value: "Latvia" },
  { label: "Lebanon", value: "Lebanon" },
  { label: "Lesotho", value: "Lesotho" },
  { label: "Liberia", value: "Liberia" },
  { label: "Libya", value: "Libya" },
  { label: "Liechtenstein", value: "Liechtenstein" },
  { label: "Lithuania", value: "Lithuania" },

  { label: "Luxembourg", value: "Luxembourg" },
  { label: "Madagascar", value: "Madagascar" },
  { label: "Malawi", value: "Malawi" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Maldives", value: "Maldives" },
  { label: "Mali", value: "Mali" },
  { label: "Malta", value: "Malta" },
  { label: "Marshall Islands", value: "Marshall Islands" },
  { label: "Mauritania", value: "Mauritania" },
  { label: "Mauritius", value: "Mauritius" },
  { label: "Mexico", value: "Mexico" },
  { label: "Micronesia", value: "Micronesia" },
  { label: "Moldova", value: "Moldova" },
  { label: "Monaco", value: "Monaco" },
  { label: "Mongolia", value: "Mongolia" },
  { label: "Montenegro", value: "Montenegro" },
  { label: "Morocco", value: "Morocco" },
  { label: "Mozambique", value: "Mozambique" },
  { label: "Myanmar", value: "Myanmar" },
  { label: "Namibia", value: "Namibia" },
  { label: "Nauru", value: "Nauru" },
  { label: "Nepal", value: "Nepal" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Nicaragua", value: "Nicaragua" },
  { label: "Niger", value: "Niger" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "North Korea", value: "North Korea" },
  { label: "North Macedonia", value: "North Macedonia" },
  { label: "Norway", value: "Norway" },
  { label: "Oman", value: "Oman" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "Palau", value: "Palau" },
  { label: "Palestine", value: "Palestine" },
  { label: "Panama", value: "Panama" },
  { label: "Papua New Guinea", value: "Papua New Guinea" },
  { label: "Paraguay", value: "Paraguay" },
  { label: "Peru", value: "Peru" },
  { label: "Philippines", value: "Philippines" },
  { label: "Poland", value: "Poland" },
  { label: "Portugal", value: "Portugal" },
  { label: "Qatar", value: "Qatar" },
  { label: "Romania", value: "Romania" },
  { label: "Russia", value: "Russia" },
  { label: "Rwanda", value: "Rwanda" },
  { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { label: "Saint Lucia", value: "Saint Lucia" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { label: "Samoa", value: "Samoa" },
  { label: "San Marino", value: "San Marino" },
  { label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "Senegal", value: "Senegal" },
  { label: "Serbia", value: "Serbia" },
  { label: "Seychelles", value: "Seychelles" },
  { label: "Sierra Leone", value: "Sierra Leone" },
  { label: "Singapore", value: "Singapore" },
  { label: "Slovakia", value: "Slovakia" },
  { label: "Slovenia", value: "Slovenia" },
  { label: "Solomon Islands", value: "Solomon Islands" },
  { label: "Somalia", value: "Somalia" },
  { label: "South Africa", value: "South Africa" },
  { label: "South Korea", value: "South Korea" },
  { label: "South Sudan", value: "South Sudan" },
  { label: "Spain", value: "Spain" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "Sudan", value: "Sudan" },
  { label: "Suriname", value: "Suriname" },
  { label: "Sweden", value: "Sweden" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Syria", value: "Syria" },
  { label: "Tajikistan", value: "Tajikistan" },
  { label: "Tanzania", value: "Tanzania" },
  { label: "Thailand", value: "Thailand" },
  { label: "Timor-Leste", value: "Timor-Leste" },
  { label: "Togo", value: "Togo" },
  { label: "Tonga", value: "Tonga" },
  { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  { label: "Tunisia", value: "Tunisia" },
  { label: "Turkey", value: "Turkey" },
  { label: "Turkmenistan", value: "Turkmenistan" },
  { label: "Tuvalu", value: "Tuvalu" },
  { label: "Uganda", value: "Uganda" },
  { label: "Ukraine", value: "Ukraine" },
  { label: "United Arab Emirates", value: "United Arab Emirates" },
  { label: "United Kingdom", value: "United Kingdom" },
  { label: "United States", value: "United States" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "Uzbekistan", value: "Uzbekistan" },
  { label: "Vanuatu", value: "Vanuatu" },
  { label: "Vatican City", value: "Vatican City" },
  { label: "Venezuela", value: "Venezuela" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Yemen", value: "Yemen" },
  { label: "Zambia", value: "Zambia" },
  { label: "Zimbabwe", value: "Zimbabwe" },
];

export const countriesAndStates = [
  {
    country: "Nigeria",
    states: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
      "Federal Capital Territory",
    ],
  },
  {
    country: "Afghanistan",
    states: [
      "Badakhshan",
      "Badghis",
      "Baghlan",
      "Balkh",
      "Bamyan",
      "Daykundi",
      "Farah",
      "Faryab",
      "Ghazni",
      "Ghor",
      "Helmand",
      "Herat",
      "Jowzjan",
      "Kabul",
      "Kandahar",
      "Kapisa",
      "Khost",
      "Kunar",
      "Kunduz",
      "Laghman",
      "Logar",
      "Nangarhar",
      "Nimroz",
      "Nuristan",
      "Paktia",
      "Paktika",
      "Panjshir",
      "Parwan",
      "Samangan",
      "Sar-e Pol",
      "Takhar",
      "Urozgan",
      "Wardak",
      "Zabul",
    ],
  },
  {
    country: "Albania",
    states: [
      "Berat",
      "Dibër",
      "Durrës",
      "Elbasan",
      "Fier",
      "Gjirokastër",
      "Korçë",
      "Kukës",
      "Lezhë",
      "Shkodër",
      "Tiranë",
      "Vlorë",
    ],
  },
  {
    country: "Algeria",
    states: [
      "Adrar",
      "Aïn Defla",
      "Aïn Témouchent",
      "Algiers",
      "Annaba",
      "Batna",
      "Béchar",
      "Béjaïa",
      "Biskra",
      "Blida",
      "Bordj Bou Arréridj",
      "Bouïra",
      "Boumerdès",
      "Chlef",
      "Constantine",
      "Djelfa",
      "El Bayadh",
      "El Oued",
      "El Tarf",
      "Ghardaïa",
      "Guelma",
      "Illizi",
      "Jijel",
      "Khenchela",
      "Laghouat",
      "M'Sila",
      "Mascara",
      "Médéa",
      "Mila",
      "Mostaganem",
      "Naama",
      "Oran",
      "Ouargla",
      "Oum El Bouaghi",
      "Relizane",
      "Saïda",
      "Sétif",
      "Sidi Bel Abbès",
      "Skikda",
      "Souk Ahras",
      "Tamanrasset",
      "Tébessa",
      "Tiaret",
      "Tindouf",
      "Tipaza",
      "Tissemsilt",
      "Tizi Ouzou",
      "Tlemcen",
    ],
  },
  {
    country: "Andorra",
    states: [
      "Andorra la Vella",
      "Canillo",
      "Encamp",
      "Escaldes-Engordany",
      "La Massana",
      "Ordino",
      "Sant Julià de Lòria",
    ],
  },
  {
    country: "Angola",
    states: [
      "Bengo",
      "Benguela",
      "Bié",
      "Cabinda",
      "Cuando Cubango",
      "Cuanza Norte",
      "Cuanza Sul",
      "Cunene",
      "Huambo",
      "Huíla",
      "Luanda",
      "Lunda Norte",
      "Lunda Sul",
      "Malanje",
      "Moxico",
      "Namibe",
      "Uíge",
      "Zaire",
    ],
  },
  {
    country: "Antigua and Barbuda",
    states: [
      "Barbuda",
      "Redonda",
      "Saint George",
      "Saint John",
      "Saint Mary",
      "Saint Paul",
      "Saint Peter",
      "Saint Philip",
    ],
  },
  {
    country: "Argentina",
    states: [
      "Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Córdoba",
      "Corrientes",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquén",
      "Río Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego",
      "Tucumán",
    ],
  },
  {
    country: "Armenia",
    states: [
      "Aragatsotn",
      "Ararat",
      "Armavir",
      "Gegharkunik",
      "Kotayk",
      "Lori",
      "Shirak",
      "Syunik",
      "Tavush",
      "Vayots Dzor",
      "Yerevan",
    ],
  },
  {
    country: "Australia",
    states: [
      "Australian Capital Territory",
      "New South Wales",
      "Northern Territory",
      "Queensland",
      "South Australia",
      "Tasmania",
      "Victoria",
      "Western Australia",
    ],
  },
  {
    country: "Austria",
    states: [
      "Burgenland",
      "Carinthia",
      "Lower Austria",
      "Salzburg",
      "Styria",
      "Tyrol",
      "Upper Austria",
      "Vienna",
      "Vorarlberg",
    ],
  },
  {
    country: "Azerbaijan",
    states: [
      "Absheron",
      "Agstafa",
      "Agsu",
      "Astara",
      "Balakan",
      "Barda",
      "Beylagan",
      "Bilasuvar",
      "Dashkasan",
      "Fizuli",
      "Ganja",
      "Goranboy",
      "Goychay",
      "Goygol",
      "Hajigabul",
      "Imishli",
      "Ismailli",
      "Jabrayil",
      "Jalilabad",
      "Kalbajar",
      "Kangarli",
      "Khachmaz",
      "Khizi",
      "Khojali",
      "Kurdamir",
      "Lachin",
      "Lankaran",
      "Lankaran",
      "Lerik",
      "Masally",
      "Mingachevir",
      "Nakhchivan",
      "Neftchala",
      "Oghuz",
      "Qabala",
      "Qakh",
      "Qazakh",
      "Quba",
      "Qubadli",
      "Qusar",
      "Saatly",
      "Sabirabad",
      "Shaki",
      "Shaki",
      "Shamakhi",
      "Shamkir",
      "Shirvan",
      "Siazan",
      "Sumqayit",
      "Tartar",
      "Tovuz",
      "Ujar",
      "Yardymli",
      "Yevlakh",
      "Zangilan",
      "Zaqatala",
      "Zardab",
    ],
  },
  {
    country: "Bahamas",
    states: [
      "Acklins",
      "Berry Islands",
      "Bimini",
      "Black Point",
      "Cat Island",
      "Central Abaco",
      "Central Andros",
      "Central Eleuthera",
      "City of Freeport",
      "Crooked Island and Long Cay",
      "East Grand Bahama",
      "Exuma",
      "Grand Cay",
      "Harbour Island",
      "Hope Town",
      "Inagua",
      "Long Island",
      "Mangrove Cay",
      "Mayaguana",
      "Moore's Island",
      "North Abaco",
      "North Andros",
      "North Eleuthera",
      "Ragged Island",
      "Rum Cay",
      "San Salvador",
      "South Abaco",
      "South Andros",
      "South Eleuthera",
      "Spanish Wells",
      "West Grand Bahama",
    ],
  },
  {
    country: "Bahrain",
    states: [
      "Capital Governorate",
      "Central Governorate",
      "Muharraq Governorate",
      "Northern Governorate",
      "Southern Governorate",
    ],
  },
  {
    country: "Bangladesh",
    states: [
      "Barisal Division",
      "Chittagong Division",
      "Dhaka Division",
      "Khulna Division",
      "Mymensingh Division",
      "Rajshahi Division",
      "Rangpur Division",
      "Sylhet Division",
    ],
  },
  {
    country: "Barbados",
    states: [
      "Christ Church",
      "Saint Andrew",
      "Saint George",
      "Saint James",
      "Saint John",
      "Saint Joseph",
      "Saint Lucy",
      "Saint Michael",
      "Saint Peter",
      "Saint Philip",
      "Saint Thomas",
    ],
  },
  {
    country: "Belarus",
    states: [
      "Brest Region",
      "Gomel Region",
      "Grodno Region",
      "Minsk",
      "Minsk Region",
      "Mogilev Region",
      "Vitebsk Region",
    ],
  },
  {
    country: "Belgium",
    states: [
      "Antwerp",
      "Brussels-Capital Region",
      "East Flanders",
      "Flemish Brabant",
      "Hainaut",
      "Liège",
      "Limburg",
      "Luxembourg",
      "Namur",
      "Walloon Brabant",
      "West Flanders",
    ],
  },
  {
    country: "Belize",
    states: [
      "Belize",
      "Cayo",
      "Corozal",
      "Orange Walk",
      "Stann Creek",
      "Toledo",
    ],
  },
  {
    country: "Benin",
    states: [
      "Alibori",
      "Atakora",
      "Atlantique",
      "Borgou",
      "Collines",
      "Donga",
      "Kouffo",
      "Littoral",
      "Mono",
      "Ouémé",
      "Plateau",
      "Zou",
    ],
  },
  {
    country: "Bhutan",
    states: [
      "Bumthang",
      "Chukha",
      "Dagana",
      "Gasa",
      "Haa",
      "Lhuntse",
      "Mongar",
      "Paro",
      "Pemagatshel",
      "Punakha",
      "Samdrup Jongkhar",
      "Samtse",
      "Sarpang",
      "Thimphu",
      "Trashigang",
      "Trongsa",
      "Tsirang",
      "Wangdue Phodrang",
      "Zhemgang",
    ],
  },
  {
    country: "Bolivia",
    states: [
      "Beni",
      "Chuquisaca",
      "Cochabamba",
      "La Paz",
      "Oruro",
      "Pando",
      "Potosí",
      "Santa Cruz",
      "Tarija",
    ],
  },
  {
    country: "Bosnia and Herzegovina",
    states: [
      "Brčko District",
      "Federation of Bosnia and Herzegovina",
      "Republika Srpska",
    ],
  },
  {
    country: "Botswana",
    states: [
      "Central District",
      "Ghanzi District",
      "Kgalagadi District",
      "Kgatleng District",
      "Kweneng District",
      "North-East District",
      "North-West District",
      "South-East District",
      "Southern District",
    ],
  },
  {
    country: "Brazil",
    states: [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Espírito Santo",
      "Federal District",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins",
    ],
  },
  {
    country: "Brunei",
    states: ["Belait", "Brunei-Muara", "Temburong", "Tutong"],
  },
  {
    country: "Bulgaria",
    states: [
      "Blagoevgrad Province",
      "Burgas Province",
      "Dobrich Province",
      "Gabrovo Province",
      "Haskovo Province",
      "Kardzhali Province",
      "Kyustendil Province",
      "Lovech Province",
      "Montana Province",
      "Pazardzhik Province",
      "Pernik Province",
      "Pleven Province",
      "Plovdiv Province",
      "Razgrad Province",
      "Ruse Province",
      "Shumen Province",
      "Silistra Province",
      "Sliven Province",
      "Smolyan Province",
      "Sofia City Province",
      "Sofia Province",
      "Stara Zagora Province",
      "Targovishte Province",
      "Varna Province",
      "Veliko Tarnovo Province",
      "Vidin Province",
      "Vratsa Province",
      "Yambol Province",
    ],
  },
  {
    country: "Burkina Faso",
    states: [
      "Balé",
      "Bam",
      "Banwa",
      "Bazèga",
      "Boucle du Mouhoun",
      "Bougouriba",
      "Boulgou",
      "Boulkiemdé",
      "Comoé",
      "Ganzourgou",
      "Gnagna",
      "Gourma",
      "Houet",
      "Ioba",
      "Kadiogo",
      "Kénédougou",
      "Komondjari",
      "Kompienga",
      "Kossi",
      "Koulpélogo",
      "Kouritenga",
      "Kourwéogo",
      "Léraba",
      "Loroum",
      "Mouhoun",
      "Nahouri",
      "Namentenga",
      "Nayala",
      "Noumbiel",
      "Oubritenga",
      "Oudalan",
      "Passoré",
      "Poni",
      "Sanguié",
      "Sanmatenga",
      "Séno",
      "Sissili",
      "Soum",
      "Sourou",
      "Tapoa",
      "Tuy",
      "Yagha",
      "Yatenga",
      "Ziro",
      "Zondoma",
      "Zoundwéogo",
    ],
  },
  {
    country: "Burundi",
    states: [
      "Bubanza",
      "Bujumbura Mairie",
      "Bujumbura Rural",
      "Bururi",
      "Cankuzo",
      "Cibitoke",
      "Gitega",
      "Karuzi",
      "Kayanza",
      "Kirundo",
      "Makamba",
      "Muramvya",
      "Muyinga",
      "Mwaro",
      "Ngozi",
      "Rumonge",
      "Rutana",
      "Ruyigi",
    ],
  },
  {
    country: "Cambodia",
    states: [
      "Banteay Meanchey",
      "Battambang",
      "Kampong Cham",
      "Kampong Chhnang",
      "Kampong Speu",
      "Kampong Thom",
      "Kampot",
      "Kandal",
      "Koh Kong",
      "Kratié",
      "Mondulkiri",
      "Oddar Meanchey",
      "Pailin",
      "Phnom Penh",
      "Preah Sihanouk",
      "Preah Vihear",
      "Pursat",
      "Ratanakiri",
      "Siem Reap",
      "Sihanoukville",
      "Stung Treng",
      "Svay Rieng",
      "Takéo",
      "Tbong Khmum",
    ],
  },
  {
    country: "Cameroon",
    states: [
      "Adamaoua",
      "Centre",
      "East",
      "Far North",
      "Littoral",
      "North",
      "Northwest",
      "South",
      "Southwest",
      "West",
    ],
  },
  {
    country: "Canada",
    states: [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Nova Scotia",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
    ],
  },
  {
    country: "Cape Verde",
    states: [
      "Boa Vista",
      "Brava",
      "Maio",
      "Mosteiros",
      "Paul",
      "Porto Novo",
      "Praia",
      "Ribeira Brava",
      "Ribeira Grande",
      "Ribeira Grande de Santiago",
      "Sal",
      "Santa Catarina",
      "Santa Catarina do Fogo",
      "Santa Cruz",
      "São Domingos",
      "São Filipe",
      "São Lourenço dos Órgãos",
      "São Miguel",
      "São Salvador do Mundo",
      "São Vicente",
      "Tarrafal",
      "Tarrafal de São Nicolau",
    ],
  },
  {
    country: "Central African Republic",
    states: [
      "Bamingui-Bangoran",
      "Bangui",
      "Basse-Kotto",
      "Haute-Kotto",
      "Haut-Mbomou",
      "Kémo",
      "Lobaye",
      "Mambéré-Kadéï",
      "Mbomou",
      "Nana-Grébizi",
      "Nana-Mambéré",
      "Ombella-M'Poko",
      "Ouaka",
      "Ouham",
      "Ouham-Pendé",
      "Sangha-Mbaéré",
      "Vakaga",
    ],
  },
  {
    country: "Chad",
    states: [
      "Bahr el Gazel",
      "Batha",
      "Borkou",
      "Chari-Baguirmi",
      "Ennedi",
      "Guéra",
      "Hadjer-Lamis",
      "Kanem",
      "Lac",
      "Logone Occidental",
      "Logone Oriental",
      "Mandoul",
      "Mayo-Kebbi Est",
      "Mayo-Kebbi Ouest",
      "Moyen-Chari",
      "N'Djamena",
      "Ouaddaï",
      "Salamat",
      "Sila",
      "Tandjilé",
      "Tibesti",
      "Wadi Fira",
    ],
  },
  {
    country: "Chile",
    states: [
      "Aisén",
      "Antofagasta",
      "Araucanía",
      "Arica y Parinacota",
      "Atacama",
      "Biobío",
      "Coquimbo",
      "Los Lagos",
      "Los Ríos",
      "Magallanes",
      "Maule",
      "Ñuble",
      "O'Higgins",
      "Santiago Metropolitan Region",
      "Tarapacá",
      "Valparaíso",
    ],
  },
  {
    country: "China",
    states: [
      "Anhui",
      "Beijing",
      "Chongqing",
      "Fujian",
      "Gansu",
      "Guangdong",
      "Guangxi",
      "Guizhou",
      "Hainan",
      "Hebei",
      "Heilongjiang",
      "Henan",
      "Hong Kong",
      "Hubei",
      "Hunan",
      "Inner Mongolia",
      "Jiangsu",
      "Jiangxi",
      "Jilin",
      "Liaoning",
      "Macau",
      "Ningxia",
      "Qinghai",
      "Shaanxi",
      "Shandong",
      "Shanghai",
      "Shanxi",
      "Sichuan",
      "Tianjin",
      "Tibet",
      "Xinjiang",
      "Yunnan",
      "Zhejiang",
    ],
  },
  {
    country: "Colombia",
    states: [
      "Amazonas",
      "Antioquia",
      "Arauca",
      "Atlántico",
      "Bogotá",
      "Bolívar",
      "Boyacá",
      "Caldas",
      "Caquetá",
      "Casanare",
      "Cauca",
      "Cesar",
      "Chocó",
      "Córdoba",
      "Cundinamarca",
      "Guainía",
      "Guaviare",
      "Huila",
      "La Guajira",
      "Magdalena",
      "Meta",
      "Nariño",
      "Norte de Santander",
      "Putumayo",
      "Quindío",
      "Risaralda",
      "San Andrés and Providencia",
      "Santander",
      "Sucre",
      "Tolima",
      "Valle del Cauca",
      "Vaupés",
      "Vichada",
    ],
  },
  {
    country: "Comoros",
    states: ["Anjouan", "Grande Comore", "Mohéli"],
  },
  {
    country: "Congo (Brazzaville)",
    states: [
      "Bouenza",
      "Brazzaville",
      "Cuvette",
      "Cuvette-Ouest",
      "Kouilou",
      "Lékoumou",
      "Likouala",
      "Niari",
      "Plateaux",
      "Pointe-Noire",
      "Pool",
      "Sangha",
    ],
  },
  {
    country: "Congo (Kinshasa)",
    states: [
      "Bas-Uele",
      "Équateur",
      "Haut-Katanga",
      "Haut-Lomami",
      "Haut-Uele",
      "Ituri",
      "Kasaï",
      "Kasaï-Central",
      "Kasaï-Oriental",
      "Kinshasa",
      "Kwango",
      "Kwilu",
      "Lomami",
      "Lualaba",
      "Mai-Ndombe",
      "Maniema",
      "Mongala",
      "Nord-Ubangi",
      "Nord-Kivu",
      "Sankuru",
      "Sud-Ubangi",
      "Sud-Kivu",
      "Tanganyika",
      "Tshopo",
      "Tshuapa",
    ],
  },
  {
    country: "Costa Rica",
    states: [
      "Alajuela",
      "Cartago",
      "Guanacaste",
      "Heredia",
      "Limón",
      "Puntarenas",
      "San José",
    ],
  },
  {
    country: "Croatia",
    states: [
      "Bjelovar-Bilogora County",
      "Brod-Posavina County",
      "Dubrovnik-Neretva County",
      "Istria County",
      "Koprivnica-Križevci County",
      "Krapina-Zagorje County",
      "Lika-Senj County",
      "Međimurje County",
      "Osijek-Baranja County",
      "Požega-Slavonia County",
      "Primorje-Gorski Kotar County",
      "Šibenik-Knin County",
      "Sisak-Moslavina County",
      "Split-Dalmatia County",
      "Varaždin County",
      "Virovitica-Podravina County",
      "Vukovar-Syrmia County",
      "Zadar County",
      "Zagreb",
      "Zagreb County",
    ],
  },
  {
    country: "Cuba",
    states: [
      "Artemisa",
      "Camagüey",
      "Ciego de Ávila",
      "Cienfuegos",
      "Granma",
      "Guantánamo",
      "Havana",
      "Holguín",
      "Isla de la Juventud",
      "Las Tunas",
      "Matanzas",
      "Mayabeque",
      "Pinar del Río",
      "Sancti Spíritus",
      "Santiago de Cuba",
      "Villa Clara",
    ],
  },
  {
    country: "Cyprus",
    states: [
      "Famagusta District",
      "Kyrenia District",
      "Larnaca District",
      "Limassol District",
      "Nicosia District",
      "Paphos District",
    ],
  },
  {
    country: "Czech Republic",
    states: [
      "Central Bohemian Region",
      "Hradec Králové Region",
      "Karlovy Vary Region",
      "Liberec Region",
      "Moravian-Silesian Region",
      "Olomouc Region",
      "Pardubice Region",
      "Plzeň Region",
      "Prague",
      "South Bohemian Region",
      "South Moravian Region",
      "Ústí nad Labem Region",
      "Vysočina Region",
      "Zlín Region",
    ],
  },
  {
    country: "Denmark",
    states: [
      "Capital Region of Denmark",
      "Central Denmark Region",
      "North Denmark Region",
      "Region of Southern Denmark",
      "Region Zealand",
    ],
  },
  {
    country: "Djibouti",
    states: ["Ali Sabieh", "Arta", "Dikhil", "Djibouti", "Obock", "Tadjourah"],
  },
  {
    country: "Dominica",
    states: [
      "Saint Andrew Parish",
      "Saint David Parish",
      "Saint George Parish",
      "Saint John Parish",
      "Saint Joseph Parish",
      "Saint Luke Parish",
      "Saint Mark Parish",
      "Saint Patrick Parish",
      "Saint Paul Parish",
      "Saint Peter Parish",
    ],
  },
  {
    country: "Dominican Republic",
    states: [
      "Azua",
      "Baoruco",
      "Barahona",
      "Dajabón",
      "Distrito Nacional",
      "Duarte",
      "El Seibo",
      "Espaillat",
      "Hato Mayor",
      "Hermanas Mirabal",
      "Independencia",
      "La Altagracia",
      "La Romana",
      "La Vega",
      "María Trinidad Sánchez",
      "Monseñor Nouel",
      "Monte Cristi",
      "Monte Plata",
      "Pedernales",
      "Peravia",
      "Puerto Plata",
      "Samaná",
      "San Cristóbal",
      "San José de Ocoa",
      "San Juan",
      "San Pedro de Macorís",
      "Sánchez Ramírez",
      "Santiago",
      "Santiago Rodríguez",
      "Santo Domingo",
      "Valverde",
    ],
  },
  {
    country: "Ecuador",
    states: [
      "Azuay",
      "Bolívar",
      "Cañar",
      "Carchi",
      "Chimborazo",
      "Cotopaxi",
      "El Oro",
      "Esmeraldas",
      "Galápagos",
      "Guayas",
      "Imbabura",
      "Loja",
      "Los Ríos",
      "Manabí",
      "Morona Santiago",
      "Napo",
      "Orellana",
      "Pastaza",
      "Pichincha",
      "Santa Elena",
      "Santo Domingo de los Tsáchilas",
      "Sucumbíos",
      "Tungurahua",
      "Zamora Chinchipe",
    ],
  },
  {
    country: "Egypt",
    states: [
      "Alexandria",
      "Aswan",
      "Asyut",
      "Beheira",
      "Beni Suef",
      "Cairo",
      "Dakahlia",
      "Damietta",
      "Faiyum",
      "Gharbia",
      "Giza",
      "Ismailia",
      "Kafr el-Sheikh",
      "Luxor",
      "Matruh",
      "Minya",
      "Monufia",
      "New Valley",
      "North Sinai",
      "Port Said",
      "Qalyubia",
      "Qena",
      "Red Sea",
      "Sharqia",
      "Sohag",
      "South Sinai",
      "Suez",
    ],
  },
  {
    country: "El Salvador",
    states: [
      "Ahuachapán",
      "Cabañas",
      "Chalatenango",
      "Cuscatlán",
      "La Libertad",
      "La Paz",
      "La Unión",
      "Morazán",
      "San Miguel",
      "San Salvador",
      "San Vicente",
      "Santa Ana",
      "Sonsonate",
      "Usulután",
    ],
  },
  {
    country: "Equatorial Guinea",
    states: [
      "Annobón",
      "Bioko Norte",
      "Bioko Sur",
      "Centro Sur",
      "Kié-Ntem",
      "Litoral",
      "Wele-Nzas",
    ],
  },
  {
    country: "Eritrea",
    states: [
      "Anseba",
      "Debub",
      "Debubawi Keyih Bahri",
      "Gash-Barka",
      "Maekel",
      "Semenawi Keyih Bahri",
    ],
  },
  {
    country: "Estonia",
    states: [
      "Harju",
      "Hiiu",
      "Ida-Viru",
      "Järva",
      "Jõgeva",
      "Lääne",
      "Lääne-Viru",
      "Põlva",
      "Pärnu",
      "Rapla",
      "Saare",
      "Tartu",
      "Valga",
      "Viljandi",
      "Võru",
    ],
  },
  {
    country: "Eswatini",
    states: ["Hhohho", "Lubombo", "Manzini", "Shiselweni"],
  },
  {
    country: "Ethiopia",
    states: [
      "Addis Ababa",
      "Afar",
      "Amhara",
      "Benishangul-Gumuz",
      "Dire Dawa",
      "Gambela",
      "Harari",
      "Oromia",
      "Sidama",
      "Somali",
      "Southern Nations, Nationalities, and Peoples'",
      "Tigray",
    ],
  },
  {
    country: "Fiji",
    states: [
      "Ba",
      "Bua",
      "Cakaudrove",
      "Kadavu",
      "Lau",
      "Lomaiviti",
      "Macuata",
      "Nadroga-Navosa",
      "Naitasiri",
      "Namosi",
      "Ra",
      "Rewa",
      "Rotuma",
      "Serua",
      "Tailevu",
    ],
  },
  {
    country: "Finland",
    states: [
      "Åland",
      "Central Finland",
      "Central Ostrobothnia",
      "Eastern Finland",
      "Kainuu",
      "Kanta-Häme",
      "Kymenlaakso",
      "Lapland",
      "North Karelia",
      "North Ostrobothnia",
      "Northern Savonia",
      "Ostrobothnia",
      "Päijänne Tavastia",
      "Pirkanmaa",
      "Satakunta",
      "South Karelia",
      "South Ostrobothnia",
      "Southern Savonia",
      "Uusimaa",
      "Varsinais-Suomi",
    ],
  },
  {
    country: "France",
    states: [
      "Auvergne-Rhône-Alpes",
      "Bourgogne-Franche-Comté",
      "Brittany",
      "Centre-Val de Loire",
      "Corsica",
      "Grand Est",
      "Hauts-de-France",
      "Île-de-France",
      "Normandy",
      "Nouvelle-Aquitaine",
      "Occitanie",
      "Pays de la Loire",
      "Provence-Alpes-Côte d'Azur",
    ],
  },
  {
    country: "Gabon",
    states: [
      "Estuaire",
      "Haut-Ogooué",
      "Moyen-Ogooué",
      "Ngounié",
      "Nyanga",
      "Ogooué-Ivindo",
      "Ogooué-Lolo",
      "Ogooué-Maritime",
      "Woleu-Ntem",
    ],
  },
  {
    country: "Gambia",
    states: [
      "Banjul",
      "Central River",
      "Lower River",
      "North Bank",
      "Upper River",
      "West Coast",
    ],
  },
  {
    country: "Georgia",
    states: [
      "Abkhazia",
      "Adjara",
      "Guria",
      "Imereti",
      "Kakheti",
      "Kvemo Kartli",
      "Mtskheta-Mtianeti",
      "Racha-Lechkhumi and Kvemo Svaneti",
      "Samegrelo-Zemo Svaneti",
      "Samtskhe-Javakheti",
      "Shida Kartli",
      "Tbilisi",
    ],
  },
  {
    country: "Germany",
    states: [
      "Baden-Württemberg",
      "Bavaria",
      "Berlin",
      "Brandenburg",
      "Bremen",
      "Hamburg",
      "Hesse",
      "Lower Saxony",
      "Mecklenburg-Western Pomerania",
      "North Rhine-Westphalia",
      "Rhineland-Palatinate",
      "Saarland",
      "Saxony",
      "Saxony-Anhalt",
      "Schleswig-Holstein",
      "Thuringia",
    ],
  },
  {
    country: "Ghana",
    states: [
      "Ahafo",
      "Ashanti",
      "Bono",
      "Bono East",
      "Central",
      "Eastern",
      "Greater Accra",
      "Northern",
      "Oti",
      "Savannah",
      "Upper East",
      "Upper West",
      "Volta",
      "Western",
      "Western North",
    ],
  },
  {
    country: "Greece",
    states: [
      "Aegean Islands",
      "Attica",
      "Central Greece",
      "Central Macedonia",
      "Crete",
      "Eastern Macedonia and Thrace",
      "Epirus",
      "Ionian Islands",
      "Peloponnese",
      "Thessaly",
      "Western Greece",
      "Western Macedonia",
    ],
  },
  {
    country: "Grenada",
    states: [
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint John",
      "Saint Mark",
      "Saint Patrick",
    ],
  },
  {
    country: "Guatemala",
    states: [
      "Alta Verapaz",
      "Baja Verapaz",
      "Chimaltenango",
      "Chiquimula",
      "El Progreso",
      "Escuintla",
      "Guatemala",
      "Huehuetenango",
      "Izabal",
      "Jalapa",
      "Jutiapa",
      "Petén",
      "Quetzaltenango",
      "Quiché",
      "Retalhuleu",
      "Sacatepéquez",
      "San Marcos",
      "Santa Rosa",
      "Sololá",
      "Suchitepéquez",
      "Totonicapán",
      "Zacapa",
    ],
  },
  {
    country: "Guinea",
    states: [
      "Beyla",
      "Boffa",
      "Boké",
      "Conakry",
      "Coyah",
      "Dabola",
      "Dalaba",
      "Dinguiraye",
      "Dubréka",
      "Faranah",
      "Forécariah",
      "Fria",
      "Gaoual",
      "Kankan",
      "Kérouané",
      "Kindia",
      "Kissidougou",
      "Koubia",
      "Koundara",
      "Kouroussa",
      "Labé",
      "Lelouma",
      "Lola",
      "Macenta",
      "Mali",
      "Mamou",
      "Mandiana",
      "Nzérékoré",
      "Pita",
      "Siguiri",
      "Télimélé",
      "Tougué",
      "Yomou",
    ],
  },
  {
    country: "Guinea-Bissau",
    states: [
      "Bafatá",
      "Biombo",
      "Bissau",
      "Bolama",
      "Cacheu",
      "Gabú",
      "Oio",
      "Quinara",
      "Tombali",
    ],
  },
  {
    country: "Guyana",
    states: [
      "Barima-Waini",
      "Cuyuni-Mazaruni",
      "Demerara-Mahaica",
      "East Berbice-Corentyne",
      "Essequibo Islands-West Demerara",
      "Mahaica-Berbice",
      "Pomeroon-Supenaam",
      "Potaro-Siparuni",
      "Upper Demerara-Berbice",
      "Upper Takutu-Upper Essequibo",
    ],
  },
  {
    country: "Haiti",
    states: [
      "Artibonite",
      "Centre",
      "Grand'Anse",
      "Nippes",
      "Nord",
      "Nord-Est",
      "Nord-Ouest",
      "Ouest",
      "Sud",
      "Sud-Est",
    ],
  },
  {
    country: "Honduras",
    states: [
      "Atlántida",
      "Choluteca",
      "Colón",
      "Comayagua",
      "Copán",
      "Cortés",
      "El Paraíso",
      "Francisco Morazán",
      "Gracias a Dios",
      "Intibucá",
      "Islas de la Bahía",
      "La Paz",
      "Lempira",
      "Ocotepeque",
      "Olancho",
      "Santa Bárbara",
      "Valle",
      "Yoro",
    ],
  },
  {
    country: "Hungary",
    states: [
      "Bács-Kiskun",
      "Baranya",
      "Békés",
      "Békéscsaba",
      "Borsod-Abaúj-Zemplén",
      "Budapest",
      "Csongrád-Csanád",
      "Debrecen",
      "Dunaújváros",
      "Eger",
      "Fejér",
      "Győr-Moson-Sopron",
      "Hajdú-Bihar",
      "Heves",
      "Hódmezővásárhely",
      "Jász-Nagykun-Szolnok",
      "Kaposvár",
      "Kecskemét",
      "Komárom-Esztergom",
      "Miskolc",
      "Nagykanizsa",
      "Nógrád",
      "Nyíregyháza",
      "Pécs",
      "Pest",
      "Salgótarján",
      "Somogy",
      "Sopron",
      "Szabolcs-Szatmár-Bereg",
      "Szeged",
      "Székesfehérvár",
      "Szolnok",
      "Szombathely",
      "Tatabánya",
      "Tolna",
      "Vas",
      "Veszprém",
      "Zala",
    ],
  },
  {
    country: "Iceland",
    states: [
      "Austurland",
      "Höfuðborgarsvæðið",
      "Norðurland eystra",
      "Norðurland vestra",
      "Suðurland",
      "Suðurnes",
      "Vestfirðir",
      "Vesturland",
    ],
  },
  {
    country: "India",
    states: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Lakshadweep",
      "Delhi",
      "Puducherry",
    ],
  },
  {
    country: "Indonesia",
    states: [
      "Aceh",
      "Bali",
      "Bangka Belitung",
      "Banten",
      "Bengkulu",
      "Central Java",
      "Central Kalimantan",
      "Central Sulawesi",
      "East Java",
      "East Kalimantan",
      "East Nusa Tenggara",
      "Gorontalo",
      "Jakarta",
      "Jambi",
      "Lampung",
      "Maluku",
      "North Kalimantan",
      "North Maluku",
      "North Sulawesi",
      "North Sumatra",
      "Papua",
      "Riau",
      "Riau Islands",
      "Southeast Sulawesi",
      "South Kalimantan",
      "South Sulawesi",
      "South Sumatra",
      "West Java",
      "West Kalimantan",
      "West Nusa Tenggara",
      "West Papua",
      "West Sulawesi",
      "West Sumatra",
      "Yogyakarta",
    ],
  },
  {
    country: "Iran",
    states: [
      "Alborz",
      "Ardabil",
      "Bushehr",
      "Chaharmahal and Bakhtiari",
      "East Azerbaijan",
      "Esfahan",
      "Fars",
      "Gilan",
      "Golestan",
      "Hamadan",
      "Hormozgan",
      "Ilam",
      "Kerman",
      "Kermanshah",
      "Khuzestan",
      "Kohgiluyeh and Boyer-Ahmad",
      "Kurdistan",
      "Lorestan",
      "Markazi",
      "Mazandaran",
      "North Khorasan",
      "Qazvin",
      "Qom",
      "Razavi Khorasan",
      "Semnan",
      "Sistan and Baluchestan",
      "South Khorasan",
      "Tehran",
      "West Azerbaijan",
      "Yazd",
      "Zanjan",
    ],
  },
  {
    country: "Iraq",
    states: [
      "Al Anbar",
      "Al Muthanna",
      "Al Qadisiyyah",
      "Babylon",
      "Baghdad",
      "Basra",
      "Dhi Qar",
      "Diyala",
      "Duhok",
      "Erbil",
      "Karbala",
      "Kirkuk",
      "Maysan",
      "Najaf",
      "Nineveh",
      "Saladin",
      "Sulaymaniyah",
      "Wasit",
    ],
  },
  {
    country: "Ireland",
    states: [
      "Carlow",
      "Cavan",
      "Clare",
      "Cork",
      "Donegal",
      "Dublin",
      "Galway",
      "Kerry",
      "Kildare",
      "Kilkenny",
      "Laois",
      "Leitrim",
      "Limerick",
      "Longford",
      "Louth",
      "Mayo",
      "Meath",
      "Monaghan",
      "Offaly",
      "Roscommon",
      "Sligo",
      "Tipperary",
      "Waterford",
      "Westmeath",
      "Wexford",
      "Wicklow",
    ],
  },
  {
    country: "Israel",
    states: [
      "Central District",
      "Haifa District",
      "Jerusalem District",
      "Northern District",
      "Southern District",
      "Tel Aviv District",
    ],
  },
  {
    country: "Italy",
    states: [
      "Abruzzo",
      "Aosta Valley",
      "Apulia",
      "Basilicata",
      "Calabria",
      "Campania",
      "Emilia-Romagna",
      "Friuli Venezia Giulia",
      "Lazio",
      "Liguria",
      "Lombardy",
      "Marche",
      "Molise",
      "Piedmont",
      "Sardinia",
      "Sicily",
      "Trentino-South Tyrol",
      "Tuscany",
      "Umbria",
      "Veneto",
    ],
  },
  {
    country: "Jamaica",
    states: [
      "Clarendon",
      "Hanover",
      "Kingston",
      "Manchester",
      "Portland",
      "Saint Andrew",
      "Saint Ann",
      "Saint Catherine",
      "Saint Elizabeth",
      "Saint James",
      "Saint Mary",
      "Saint Thomas",
      "Trelawny",
      "Westmoreland",
    ],
  },
  {
    country: "Japan",
    states: [
      "Aichi",
      "Akita",
      "Aomori",
      "Chiba",
      "Ehime",
      "Fukui",
      "Fukuoka",
      "Fukushima",
      "Gifu",
      "Gunma",
      "Hiroshima",
      "Hokkaido",
      "Hyogo",
      "Ibaraki",
      "Ishikawa",
      "Iwate",
      "Kagawa",
      "Kagoshima",
      "Kanagawa",
      "Kochi",
      "Kumamoto",
      "Kyoto",
      "Mie",
      "Miyagi",
      "Miyazaki",
      "Nagano",
      "Nagasaki",
      "Nara",
      "Niigata",
      "Oita",
      "Okayama",
      "Okinawa",
      "Osaka",
      "Saga",
      "Saitama",
      "Shiga",
      "Shimane",
      "Shizuoka",
      "Tochigi",
      "Tokushima",
      "Tokyo",
      "Tottori",
      "Toyama",
      "Wakayama",
      "Yamagata",
      "Yamaguchi",
      "Yamanashi",
    ],
  },
  {
    country: "Jordan",
    states: [
      "Ajloun",
      "Amman",
      "Aqaba",
      "Balqa",
      "Irbid",
      "Jerash",
      "Karak",
      "Ma'an",
      "Madaba",
      "Mafraq",
      "Tafilah",
      "Zarqa",
    ],
  },
  {
    country: "Kazakhstan",
    states: [
      "Akmola",
      "Aktobe",
      "Almaty",
      "Atyrau",
      "Baikonur",
      "East Kazakhstan",
      "Jambyl",
      "Karaganda",
      "Kostanay",
      "Kyzylorda",
      "Mangystau",
      "North Kazakhstan",
      "Nur-Sultan",
      "Pavlodar",
      "Shymkent",
      "Turkistan",
      "West Kazakhstan",
    ],
  },
  {
    country: "Kenya",
    states: [
      "Baringo",
      "Bomet",
      "Bungoma",
      "Busia",
      "Elgeyo-Marakwet",
      "Embu",
      "Garissa",
      "Homa Bay",
      "Isiolo",
      "Kajiado",
      "Kakamega",
      "Kericho",
      "Kiambu",
      "Kilifi",
      "Kirinyaga",
      "Kisii",
      "Kisumu",
      "Kitui",
      "Kwale",
      "Laikipia",
      "Lamu",
      "Machakos",
      "Makueni",
      "Mandera",
      "Marsabit",
      "Meru",
      "Migori",
      "Mombasa",
      "Murang'a",
      "Nairobi",
      "Nakuru",
      "Nandi",
      "Narok",
      "Nyamira",
      "Nyandarua",
      "Nyeri",
      "Samburu",
      "Siaya",
      "Taita-Taveta",
      "Tana River",
      "Tharaka-Nithi",
      "Trans Nzoia",
      "Turkana",
      "Uasin Gishu",
      "Vihiga",
      "Wajir",
      "West Pokot",
    ],
  },
  {
    country: "Kiribati",
    states: ["Gilbert Islands", "Line Islands", "Phoenix Islands"],
  },
  {
    country: "Kuwait",
    states: [
      "Al Ahmadi",
      "Al Farwaniyah",
      "Al Asimah",
      "Al Jahra",
      "Hawalli",
      "Mubarak Al-Kabeer",
    ],
  },
  {
    country: "Kyrgyzstan",
    states: [
      "Batken",
      "Chuy",
      "Issyk-Kul",
      "Jalal-Abad",
      "Naryn",
      "Osh",
      "Talas",
    ],
  },
  {
    country: "Laos",
    states: [
      "Attapeu",
      "Bokeo",
      "Bolikhamsai",
      "Champasak",
      "Houaphanh",
      "Khammouane",
      "Luang Namtha",
      "Luang Prabang",
      "Oudomxay",
      "Phongsaly",
      "Salavan",
      "Savannakhet",
      "Sekong",
      "Vientiane",
      "Vientiane Prefecture",
      "Xaignabouli",
      "Xaisomboun",
      "Xiangkhouang",
    ],
  },
  {
    country: "Latvia",
    states: [
      "Aizkraukle",
      "Aluksne",
      "Balvi",
      "Bauska",
      "Cesis",
      "Daugavpils",
      "Dobele",
      "Gulbene",
      "Jekabpils",
      "Jelgava",
      "Jurmala",
      "Kraslava",
      "Kuldiga",
      "Liepaja",
      "Limbazi",
      "Ludza",
      "Madona",
      "Ogre",
      "Preili",
      "Rezekne",
      "Riga",
      "Saldus",
      "Talsi",
      "Tukums",
      "Valka",
      "Valmiera",
      "Ventspils",
    ],
  },
  {
    country: "Lebanon",
    states: [
      "Akkar",
      "Baalbek-Hermel",
      "Beirut",
      "Bekaa",
      "Keserwan-Jbeil",
      "Mount Lebanon",
      "North Lebanon",
      "South Lebanon",
    ],
  },
  {
    country: "Lesotho",
    states: [
      "Berea",
      "Butha-Buthe",
      "Leribe",
      "Mafeteng",
      "Maseru",
      "Mohale's Hoek",
      "Mokhotlong",
      "Qacha's Nek",
      "Quthing",
      "Thaba-Tseka",
    ],
  },
  {
    country: "Liberia",
    states: [
      "Bomi",
      "Bong",
      "Gbarpolu",
      "Grand Bassa",
      "Grand Cape Mount",
      "Grand Gedeh",
      "Grand Kru",
      "Lofa",
      "Margibi",
      "Maryland",
      "Montserrado",
      "Nimba",
      "Rivercess",
      "River Gee",
      "Sinoe",
    ],
  },
  {
    country: "Libya",
    states: [
      "Al Butnan",
      "Al Jabal al Akhdar",
      "Al Jabal al Gharbi",
      "Al Jafara",
      "Al Kufra",
      "Al Marj",
      "Al Marqab",
      "Al Wahat",
      "An Nuqat al Khams",
      "Az Zawiyah",
      "Benghazi",
      "Darnah",
      "Ghat",
      "Ghadamis",
      "Gharyan",
      "Misratah",
      "Murzuq",
      "Nalut",
      "Sabha",
      "Surt",
      "Tarhunah",
      "Tripoli",
      "Ubari",
      "Wadi al Hayat",
      "Wadi ash Shati",
      "Zliten",
    ],
  },
  {
    country: "Liechtenstein",
    states: [
      "Balzers",
      "Eschen",
      "Gamprin",
      "Mauren",
      "Planken",
      "Ruggell",
      "Schaan",
      "Schellenberg",
      "Triesen",
      "Triesenberg",
      "Vaduz",
    ],
  },
  {
    country: "Lithuania",
    states: [
      "Alytus",
      "Kaunas",
      "Klaipeda",
      "Marijampole",
      "Panevezys",
      "Siauliai",
      "Taurage",
      "Telsiai",
      "Utena",
      "Vilnius",
    ],
  },
  {
    country: "Luxembourg",
    states: [
      "Capellen",
      "Clervaux",
      "Diekirch",
      "Echternach",
      "Esch-sur-Alzette",
      "Grevenmacher",
      "Luxembourg",
      "Mersch",
      "Redange",
      "Remich",
      "Vianden",
      "Wiltz",
    ],
  },
  {
    country: "Madagascar",
    states: [
      "Antananarivo",
      "Antsiranana",
      "Fianarantsoa",
      "Mahajanga",
      "Toamasina",
      "Toliara",
    ],
  },
  {
    country: "Malawi",
    states: ["Central Region", "Northern Region", "Southern Region"],
  },
  {
    country: "Malaysia",
    states: [
      "Johor",
      "Kedah",
      "Kelantan",
      "Malacca",
      "Negeri Sembilan",
      "Pahang",
      "Penang",
      "Perak",
      "Perlis",
      "Sabah",
      "Sarawak",
      "Selangor",
      "Terengganu",
    ],
  },
  {
    country: "Maldives",
    states: [
      "Addu City",
      "Fuvahmulah City",
      "Malé City",
      "Upper North Province",
      "North Central Province",
      "Upper South Province",
      "South Central Province",
    ],
  },
  {
    country: "Mali",
    states: [
      "Bamako",
      "Gao",
      "Kayes",
      "Kidal",
      "Koulikoro",
      "Mopti",
      "Ségou",
      "Sikasso",
      "Tombouctou",
    ],
  },
  {
    country: "Malta",
    states: [
      "Attard",
      "Balzan",
      "Birgu",
      "Birkirkara",
      "Birzebbuga",
      "Cospicua",
      "Dingli",
      "Fgura",
      "Floriana",
      "Fontana",
      "Gudja",
      "Gzira",
      "Hamrun",
      "Iklin",
      "Isla",
      "Kalkara",
      "Kercem",
      "Kirkop",
      "Lija",
      "Luqa",
    ],
  },
  {
    country: "Mauritania",
    states: [
      "Adrar",
      "Assaba",
      "Brakna",
      "Dakhlet Nouadhibou",
      "Gorgol",
      "Guidimaka",
      "Hodh Ech Chargui",
      "Hodh El Gharbi",
      "Inchiri",
      "Nouakchott Nord",
      "Nouakchott Ouest",
      "Nouakchott Sud",
      "Tagant",
      "Tiris Zemmour",
      "Trarza",
    ],
  },
  {
    country: "Mauritius",
    states: [
      "Agalega Islands",
      "Beau Bassin-Rose Hill",
      "Cargados Carajos",
      "Curepipe",
      "Moka",
      "Pamplemousses",
      "Plaines Wilhems",
      "Port Louis",
      "Quatre Bornes",
      "Rodrigues Island",
      "Savanne",
      "Vacoas-Phoenix",
    ],
  },
  {
    country: "Mexico",
    states: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila",
      "Colima",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "Mexico City",
      "Mexico State",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
    ],
  },
  {
    country: "Micronesia",
    states: ["Chuuk", "Kosrae", "Pohnpei", "Yap"],
  },
  {
    country: "Moldova",
    states: [
      "Anenii Noi",
      "Bălți",
      "Basarabeasca",
      "Bender",
      "Briceni",
      "Cahul",
      "Cantemir",
      "Călărași",
      "Cimișlia",
      "Criuleni",
      "Dondușeni",
      "Drochia",
      "Dubăsari",
      "Edineț",
      "Fălești",
      "Florești",
      "Glodeni",
      "Hîncești",
      "Ialoveni",
      "Leova",
      "Nisporeni",
      "Ocnița",
      "Orhei",
      "Rezina",
      "Rîșcani",
      "Șoldănești",
      "Soroca",
      "Strășeni",
      "Ștefan Vodă",
      "Taraclia",
      "Telenești",
      "Ungheni",
    ],
  },
  {
    country: "Monaco",
    states: ["La Condamine", "Monaco-Ville", "Monte Carlo", "Fontvieille"],
  },
  {
    country: "Mongolia",
    states: [
      "Arkhangai",
      "Bayan-Ölgii",
      "Bayankhongor",
      "Bulgan",
      "Darkhan-Uul",
      "Dornod",
      "Dornogovi",
      "Dundgovi",
      "Govi-Altai",
      "Govisümber",
      "Khentii",
      "Khovd",
      "Khövsgöl",
      "Ömnögovi",
      "Orkhon",
      "Selenge",
      "Sükhbaatar",
      "Töv",
      "Uvs",
      "Zavkhan",
    ],
  },
  {
    country: "Montenegro",
    states: [
      "Andrijevica",
      "Bar",
      "Berane",
      "Bijelo Polje",
      "Budva",
      "Cetinje",
      "Danilovgrad",
      "Gusinje",
      "Herceg Novi",
      "Kolašin",
      "Kotor",
      "Mojkovac",
      "Nikšić",
      "Petnjica",
      "Plav",
      "Pljevlja",
      "Plužine",
      "Podgorica",
      "Rožaje",
      "Šavnik",
      "Tivat",
      "Ulcinj",
      "Žabljak",
    ],
  },
  {
    country: "Morocco",
    states: [
      "Casablanca-Settat",
      "Drâa-Tafilalet",
      "Dakhla-Oued Ed-Dahab",
      "Fès-Meknès",
      "Guelmim-Oued Noun",
      "Laâyoune-Sakia El Hamra",
      "Marrakech-Safi",
      "Oriental",
      "Rabat-Salé-Kénitra",
      "Souss-Massa",
      "Tanger-Tétouan-Al Hoceïma",
      "Béni Mellal-Khénifra",
    ],
  },
  {
    country: "Mozambique",
    states: [
      "Cabo Delgado",
      "Gaza",
      "Inhambane",
      "Manica",
      "Maputo City",
      "Maputo Province",
      "Nampula",
      "Niassa",
      "Sofala",
      "Tete",
      "Zambezia",
    ],
  },
  {
    country: "Namibia",
    states: [
      "Erongo",
      "Hardap",
      "Karas",
      "Kavango East",
      "Kavango West",
      "Khomas",
      "Kunene",
      "Ohangwena",
      "Omaheke",
      "Omusati",
      "Oshana",
      "Oshikoto",
      "Otjozondjupa",
      "Zambezi",
    ],
  },
  {
    country: "Nauru",
    states: [
      "Aiwo",
      "Anabar",
      "Anetan",
      "Anibare",
      "Baiti",
      "Boe",
      "Buada",
      "Denigomodu",
      "Ewa",
      "Ijuw",
      "Meneng",
      "Nibok",
      "Uaboe",
      "Yaren",
    ],
  },
  {
    country: "Nepal",
    states: [
      "Bagmati Province",
      "Gandaki Province",
      "Karnali Province",
      "Lumbini Province",
      "Madhesh Province",
      "Province No. 1",
      "Sudurpashchim Province",
    ],
  },
  {
    country: "Netherlands",
    states: [
      "Drenthe",
      "Flevoland",
      "Friesland",
      "Gelderland",
      "Groningen",
      "Limburg",
      "North Brabant",
      "North Holland",
      "Overijssel",
      "South Holland",
      "Utrecht",
      "Zeeland",
    ],
  },
  {
    country: "New Zealand",
    states: [
      "Auckland",
      "Bay of Plenty",
      "Canterbury",
      "Gisborne",
      "Hawke's Bay",
      "Manawatu-Wanganui",
      "Marlborough",
      "Nelson",
      "Northland",
      "Otago",
      "Southland",
      "Taranaki",
      "Tasman",
      "Waikato",
      "Wellington",
      "West Coast",
    ],
  },
  {
    country: "Nicaragua",
    states: [
      "Boaco",
      "Carazo",
      "Chinandega",
      "Chontales",
      "Estelí",
      "Granada",
      "Jinotega",
      "León",
      "Madriz",
      "Managua",
      "Masaya",
      "Matagalpa",
      "Nueva Segovia",
      "Río San Juan",
      "Rivas",
      "South Caribbean Coast",
      "North Caribbean Coast",
    ],
  },
  {
    country: "Niger",
    states: [
      "Agadez",
      "Diffa",
      "Dosso",
      "Maradi",
      "Tahoua",
      "Tillabéri",
      "Zinder",
      "Niamey",
    ],
  },

  {
    country: "North Korea",
    states: [
      "Chagang",
      "North Hamgyong",
      "South Hamgyong",
      "North Hwanghae",
      "South Hwanghae",
      "Kangwon",
      "North Pyongan",
      "South Pyongan",
      "Ryanggang",
    ],
  },
  {
    country: "North Macedonia",
    states: [
      "Eastern",
      "Northeastern",
      "Pelagonia",
      "Polog",
      "Skopje",
      "Southeastern",
      "Southwestern",
      "Vardar",
    ],
  },
  {
    country: "Norway",
    states: [
      "Agder",
      "Innlandet",
      "Møre og Romsdal",
      "Nordland",
      "Oslo",
      "Rogaland",
      "Troms og Finnmark",
      "Trøndelag",
      "Vestfold og Telemark",
      "Vestland",
      "Viken",
    ],
  },
];

export const levels = [
  "Level 4 & Above",
  "Level 3 & Above",
  "Level 2 & Above",
  "Level 1 & Above",
];

export const dashboardLinks = [
  { id: 1, name: "jobs", link: "/dashboard/job" },

  {
    id: 2,
    name: "experts",
    link: "/dashboard/expert",
  },

  {
    id: 3,
    name: "materials",
    link: "/dashboard/material",
  },
  {
    id: 4,
    name: "leads",
    link: "/dashboard/lead",
  },
];

export const buildingMaterials = [
  {
    id: 1,
    name: "Cement",
    subCategory: [
      "Ordinary Portland Cement",
      "White Cement",
      "Rapid Hardening Cement",
    ],
  },
  {
    id: 2,
    name: "Bricks",
    subCategory: ["Clay Bricks", "Concrete Bricks", "Fly Ash Bricks"],
  },
  {
    id: 3,
    name: "Concrete",
    subCategory: [
      "Reinforced Concrete",
      "Precast Concrete",
      "Lightweight Concrete",
    ],
  },
  {
    id: 4,
    name: "Steel",
    subCategory: ["Structural Steel", "Reinforcing Steel", "Stainless Steel"],
  },
  {
    id: 5,
    name: "Sand",
    subCategory: ["River Sand", "Pit Sand", "M-Sand"],
  },
  {
    id: 6,
    name: "Gravel",
    subCategory: ["Pea Gravel", "Crushed Stone", "Bank Gravel"],
  },
  {
    id: 7,
    name: "Glass",
    subCategory: ["Float Glass", "Tempered Glass", "Laminated Glass"],
  },
  {
    id: 8,
    name: "Wood",
    subCategory: ["Softwood", "Hardwood", "Plywood"],
  },
  {
    id: 9,
    name: "Tiles",
    subCategory: ["Ceramic Tiles", "Porcelain Tiles", "Vinyl Tiles"],
  },
  {
    id: 10,
    name: "Insulation",
    subCategory: [
      "Fiberglass Insulation",
      "Foam Board Insulation",
      "Spray Foam Insulation",
    ],
  },
  {
    id: 11,
    name: "Plasterboard",
    subCategory: [
      "Moisture-Resistant Plasterboard",
      "Fire-Resistant Plasterboard",
      "Acoustic Plasterboard",
    ],
  },
  {
    id: 12,
    name: "Paint",
    subCategory: ["Oil-Based Paint", "Water-Based Paint", "Acrylic Paint"],
  },
];

export const JobLinks = [
  { id: 1, name: "lead", link: "/dashboard/job/lead" },
  { id: 2, name: "new", link: "/dashboard/job/new" },

  {
    id: 3,
    name: "active jobs",
    link: "/dashboard/job/active",
  },

  {
    id: 4,
    name: "overdue jobs",
    link: "/dashboard/job/overdue",
  },
  {
    id: 5,
    name: "paused jobs",
    link: "/dashboard/job/paused",
  },
  {
    id: 6,
    name: "completed jobs",
    link: "/dashboard/job/completed",
  },
];

export const ProjectLinks = [
  { id: 1, name: "new", link: "/dahboard/project/new" },

  {
    id: 2,
    name: "active projects",
    link: "/dashboard/project/active",
  },

  {
    id: 3,
    name: "overdue projects",
    link: "/dashboard/project/overdue",
  },
  {
    id: 4,
    name: "paused projects",
    link: "/dashboard/project/paused",
  },
  {
    id: 5,
    name: "completed projects",
    link: "/dashboard/project/completed",
  },
];

export const reportLinks = [
  {
    id: 1,
    name: "Jobs",
    link: "/dashboard/report",
  },
  {
    id: 2,
    name: "Earning",
    link: "/dashboard/report/earnings",
  },

  {
    id: 3,
    name: "Projects",
    link: "/dashboard/report/projects",
  },
  {
    id: 4,
    name: "Insights",
    link: "/dashboard/report/insights",
  },
  {
    id: 3,
    name: "Target",
    link: "/dashboard/service/target",
  },
];

export const profileLinks = [
  {
    id: 1,
    name: "Personal Profile",
  },
  {
    id: 2,
    name: "Log In & Security",
  },
  {
    id: 3,
    name: "Message & Notification",
  },
];
